app/front/views.py
from flask import Blueprint, render_template, request


front_bp = Blueprint(
    "front_bp",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/front/static",
)


@front_bp.route("/")
def index():
    return render_template("index.html")


@front_bp.route('/signup', methods=['GET', 'POST'])
def register():
    return render_template('register.html')

@front_bp.route('/about')
def about():
    return render_template('about.html')

@front_bp.route('/contact', methods=['GET', 'POST'])
def contact():
    return render_template('contact.html')

app/front/templates/about.html
{% extends "base.html" %}

{% block main_content %}
<h1>About Page</h1>
{% endblock %}

app/front/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      href="https://fonts.googleapis.com/css?family=Arimo|Modak|Noticia+Text&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/style.css') }}"
    />
    <title>ShadeTree</title>
  </head>
  <body>
    <header id="header">
      <div class="branding">
        <h1><a href="#">ShadeTree</a></h1>
      </div>
      <div>
        <nav id="nav-bar">
          <ul>
            <li><a href="{{ url_for('front_bp.register') }}">Sign Up</a></li>
            <li><a href="{{ url_for('front_bp.about') }}">About</a></li>
            <li><a href="{{ url_for('front_bp.contact') }}">Contact</a></li>
          </ul>
        </nav>
      </div>
    </header>
    {% block main_content %}
    {% endblock %}
    <footer id="footer">
      <div>
        <p>Footer section goes here</p>
      </div>
    </footer>
  </body>
</html>

app/front/templates/contact.html
{% extends "base.html" %}

{% block main_content %}
<h1>Contact Page</h1>
{% endblock %}

app/front/templates/index.html
{% extends "base.html" %}

{% block main_content %}
    <section id="hero">
      <div>
        <p>Hero section goes here.</p>
      </div>
    </section>
    <section id="features">
      <div>
        <p>Features Section goes here.</p>
      </div>
    </section>
    <section id="testimonials">
      <div>
        <p>Testimonials go here</p>
      </div>
    </section>
{% endblock %}
   

app/front/templates/register.html
{% extends "base.html" %}

{% block main_content %}
<h1>Signup Page</h1>
{% endblock %}